// Bank soal Informatika SMP — 100 soal per jenjang.
// Format: [pertanyaan, JAWABAN BENAR, salah1, salah2, salah3]
// Jawaban benar selalu ditulis di posisi ke-2; urutan pilihan diacak otomatis saat main.
const BANK_SOAL = {
  kelas7: [
    ['Kata "komputer" berasal dari bahasa Latin "computare" yang berarti...', 'Menghitung', 'Menulis', 'Menyimpan', 'Menggambar'],
    ['Tiga komponen utama sistem komputer adalah...', 'Hardware, software, dan brainware', 'Monitor, keyboard, dan mouse', 'RAM, ROM, dan CPU', 'Windows, Linux, dan Android'],
    ['Hardware (perangkat keras) adalah...', 'Bagian komputer yang berwujud fisik dan dapat disentuh', 'Program yang mengatur kerja komputer', 'Orang yang mengoperasikan komputer', 'Data yang tersimpan di internet'],
    ['Software (perangkat lunak) adalah...', 'Kumpulan program/instruksi yang menjalankan komputer dan tidak dapat disentuh', 'Bagian fisik komputer di dalam casing', 'Kabel yang menghubungkan perangkat', 'Pengguna yang memakai komputer'],
    ['Brainware adalah...', 'Manusia yang mengoperasikan dan mengelola komputer', 'Prosesor sebagai otak komputer', 'Software antivirus', 'Memori utama komputer'],
    ['Manakah yang termasuk brainware?', 'Programmer', 'Printer', 'Windows', 'Flashdisk'],
    ['Perangkat input berfungsi untuk...', 'Memasukkan data atau perintah ke komputer', 'Menampilkan hasil pengolahan data', 'Menyimpan data secara permanen', 'Mendinginkan komponen komputer'],
    ['Manakah yang termasuk perangkat input?', 'Keyboard', 'Monitor', 'Speaker', 'Printer'],
    ['Fungsi utama mouse adalah...', 'Menggerakkan pointer dan memilih objek di layar', 'Mencetak dokumen', 'Menampilkan gambar', 'Menyimpan file'],
    ['Scanner berfungsi untuk...', 'Mengubah dokumen atau foto fisik menjadi file digital', 'Mencetak dokumen ke kertas', 'Memperbesar suara', 'Menyimpan data sementara'],
    ['Microphone termasuk perangkat... karena berfungsi memasukkan suara.', 'Input', 'Output', 'Proses', 'Penyimpanan'],
    ['Webcam berfungsi untuk...', 'Merekam gambar atau video ke komputer', 'Menampilkan video ke dinding', 'Mencetak foto', 'Mendinginkan prosesor'],
    ['Perangkat output berfungsi untuk...', 'Menampilkan atau mengeluarkan hasil pengolahan data', 'Memasukkan data ke komputer', 'Mengolah data menjadi informasi', 'Menyimpan data cadangan'],
    ['Manakah yang termasuk perangkat output?', 'Printer', 'Keyboard', 'Scanner', 'Mouse'],
    ['Monitor berfungsi untuk...', 'Menampilkan teks, gambar, dan video hasil olahan komputer', 'Memasukkan suara', 'Menyimpan file', 'Mencetak dokumen'],
    ['Speaker dan headphone berfungsi untuk...', 'Mengeluarkan suara dari komputer', 'Merekam suara', 'Mengetik teks', 'Memindai gambar'],
    ['Proyektor berfungsi untuk...', 'Menampilkan layar komputer ke layar lebar atau dinding', 'Mencetak dokumen', 'Memindai dokumen', 'Menyimpan data'],
    ['Printer berfungsi untuk...', 'Mencetak dokumen atau gambar ke kertas', 'Menampilkan gambar ke dinding', 'Memindai dokumen', 'Merekam video'],
    ['Layar sentuh (touchscreen) termasuk perangkat...', 'Input sekaligus output', 'Input saja', 'Output saja', 'Penyimpanan'],
    ['CPU merupakan singkatan dari...', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Control Power Unit'],
    ['Komponen yang sering disebut "otak komputer" adalah...', 'Prosesor (CPU)', 'RAM', 'Harddisk', 'Power supply'],
    ['ALU (Arithmetic Logic Unit) pada prosesor berfungsi untuk...', 'Melakukan operasi aritmetika dan logika', 'Mengatur aliran listrik', 'Menyimpan file permanen', 'Menampilkan gambar'],
    ['CU (Control Unit) pada prosesor berfungsi untuk...', 'Mengatur dan mengendalikan jalannya instruksi', 'Menghitung penjumlahan saja', 'Menyimpan data permanen', 'Mencetak hasil'],
    ['Kecepatan prosesor biasanya diukur dalam satuan...', 'GHz (gigahertz)', 'GB (gigabyte)', 'dpi', 'Watt'],
    ['Contoh merek produsen prosesor komputer adalah...', 'Intel dan AMD', 'Windows dan Linux', 'Epson dan Canon', 'Chrome dan Firefox'],
    ['RAM merupakan singkatan dari...', 'Random Access Memory', 'Read Access Memory', 'Run All Memory', 'Rapid Action Machine'],
    ['Sifat RAM adalah...', 'Menyimpan data sementara dan hilang saat komputer mati', 'Menyimpan data permanen', 'Hanya dapat dibaca', 'Menyimpan data di internet'],
    ['ROM (Read Only Memory) berisi...', 'Instruksi dasar komputer seperti BIOS', 'Dokumen milik pengguna', 'Foto dan video', 'Aplikasi game'],
    ['Harddisk (HDD) berfungsi sebagai...', 'Media penyimpanan data permanen', 'Memori sementara', 'Pemroses data', 'Pendingin komputer'],
    ['Kelebihan SSD dibandingkan HDD adalah...', 'Lebih cepat karena memakai chip tanpa piringan berputar', 'Lebih lambat tetapi lebih murah', 'Hanya bisa membaca data', 'Membutuhkan kaset'],
    ['Flashdisk termasuk perangkat...', 'Penyimpanan portabel yang dihubungkan lewat port USB', 'Input suara', 'Output gambar', 'Pemroses data'],
    ['Motherboard adalah...', 'Papan sirkuit utama tempat semua komponen terpasang dan terhubung', 'Kipas pendingin prosesor', 'Layar komputer', 'Sistem operasi'],
    ['Power supply (PSU) berfungsi untuk...', 'Menyalurkan daya listrik ke komponen komputer', 'Menyimpan data', 'Menampilkan gambar', 'Mengetik huruf'],
    ['VGA card (kartu grafis) berfungsi untuk...', 'Mengolah dan menampilkan grafis ke monitor', 'Mengolah suara', 'Menyimpan data', 'Menghubungkan ke jaringan'],
    ['Sound card berfungsi untuk...', 'Mengolah data audio/suara', 'Mengolah gambar', 'Mengatur listrik', 'Mencetak dokumen'],
    ['Heatsink dan kipas pada prosesor berfungsi untuk...', 'Mendinginkan prosesor agar tidak terlalu panas', 'Menyimpan data', 'Mempercepat internet', 'Menambah memori'],
    ['LAN card (NIC) berfungsi untuk...', 'Menghubungkan komputer ke jaringan', 'Mengolah suara', 'Menampilkan gambar', 'Mencetak dokumen'],
    ['Casing komputer berfungsi sebagai...', 'Wadah pelindung komponen di dalam komputer', 'Perangkat lunak', 'Perangkat input', 'Perangkat output'],
    ['UPS berfungsi untuk...', 'Menyediakan listrik cadangan sementara saat listrik padam', 'Menambah kapasitas RAM', 'Mencetak dokumen', 'Memindai gambar'],
    ['Port USB pada komputer digunakan untuk...', 'Menghubungkan perangkat seperti flashdisk, mouse, dan keyboard', 'Menyambung listrik PLN', 'Hanya menyambung monitor', 'Mengisi tinta printer'],
    ['Port HDMI digunakan untuk...', 'Mengirim gambar dan suara digital ke monitor, TV, atau proyektor', 'Menyambung keyboard', 'Menyambung listrik', 'Menyambung kabel telepon'],
    ['Satuan data terkecil dalam komputer adalah...', 'Bit', 'Byte', 'Kilobyte', 'Megabyte'],
    ['1 byte sama dengan...', '8 bit', '4 bit', '10 bit', '16 bit'],
    ['1 kilobyte (KB) sama dengan...', '1024 byte', '100 byte', '8 byte', '1024 megabyte'],
    ['Urutan satuan data dari yang terkecil ke terbesar adalah...', 'KB, MB, GB, TB', 'GB, MB, KB, TB', 'TB, GB, MB, KB', 'MB, KB, TB, GB'],
    ['Bilangan biner yang digunakan komputer hanya terdiri dari angka...', '0 dan 1', '0 sampai 9', '1 dan 2', 'A sampai F'],
    ['Sistem operasi adalah software yang...', 'Mengelola hardware dan menjadi penghubung antara pengguna dan komputer', 'Hanya digunakan untuk mengetik', 'Hanya digunakan untuk bermain game', 'Hanya digunakan untuk menghapus virus'],
    ['Manakah yang merupakan sistem operasi komputer?', 'Windows', 'Microsoft Word', 'Google Chrome', 'WinRAR'],
    ['Manakah yang merupakan sistem operasi pada HP?', 'Android', 'Microsoft Excel', 'Adobe Photoshop', 'VLC Media Player'],
    ['Sistem operasi buatan Apple untuk iPhone adalah...', 'iOS', 'Android', 'Windows', 'Ubuntu'],
    ['Linux dikenal sebagai sistem operasi yang bersifat...', 'Open source, kode sumbernya boleh dipelajari dan dikembangkan', 'Tertutup dan wajib dibeli mahal', 'Khusus untuk printer', 'Aplikasi pengolah kata'],
    ['Software aplikasi adalah...', 'Program untuk membantu pengguna menyelesaikan tugas tertentu', 'Program yang mengatur seluruh hardware', 'Komponen fisik komputer', 'Kabel penghubung'],
    ['Aplikasi pengolah kata contohnya adalah...', 'Microsoft Word', 'Microsoft Excel', 'Windows', 'WinRAR'],
    ['Aplikasi pengolah angka (spreadsheet) contohnya adalah...', 'Microsoft Excel', 'Microsoft Word', 'Paint', 'VLC Media Player'],
    ['Aplikasi untuk membuat presentasi contohnya adalah...', 'Microsoft PowerPoint', 'Microsoft Excel', 'Notepad', 'Kalkulator'],
    ['Aplikasi untuk menjelajah internet (web browser) contohnya adalah...', 'Google Chrome', 'Microsoft Word', 'Adobe Photoshop', 'WinRAR'],
    ['Aplikasi pengolah gambar contohnya adalah...', 'GIMP', 'Microsoft Excel', 'Notepad', 'Mozilla Firefox'],
    ['Aplikasi pemutar musik dan video contohnya adalah...', 'VLC Media Player', 'Microsoft Excel', 'Microsoft PowerPoint', 'Notepad'],
    ['Software utilitas adalah software yang...', 'Membantu merawat dan mengoptimalkan kinerja komputer', 'Digunakan untuk bermain game', 'Digunakan untuk mengetik surat', 'Merupakan sistem operasi utama'],
    ['Manakah yang termasuk software antivirus?', 'Avast', 'WinRAR', 'Paint', 'Microsoft Word'],
    ['Software untuk mengompres (memperkecil) file contohnya adalah...', '7-Zip', 'Paint', 'VLC Media Player', 'PowerPoint'],
    ['Manakah yang termasuk bahasa pemrograman?', 'Python', 'Windows', 'Microsoft Excel', 'Google Chrome'],
    ['Driver adalah software yang berfungsi...', 'Agar sistem operasi dapat mengenali dan menggunakan hardware', 'Untuk mengedit foto', 'Untuk bermain game', 'Untuk merusak file'],
    ['Freeware adalah software yang...', 'Dapat digunakan secara gratis', 'Harus dibeli terlebih dahulu', 'Merupakan hasil bajakan', 'Pasti berisi virus'],
    ['Menggunakan software bajakan sebaiknya dihindari karena...', 'Melanggar hak cipta dan berisiko mengandung virus', 'Lebih cepat dari versi asli', 'Lebih aman dari versi asli', 'Diwajibkan oleh pemerintah'],
    ['Booting adalah...', 'Proses menyalakan komputer hingga siap digunakan', 'Proses mematikan komputer', 'Proses menyimpan file', 'Proses mencetak dokumen'],
    ['Cara mematikan komputer yang benar adalah...', 'Melalui menu Shut Down pada sistem operasi', 'Mencabut kabel listrik langsung', 'Menekan tombol reset', 'Menutup layar monitor saja'],
    ['Warm boot adalah...', 'Menyalakan ulang (restart) komputer yang sedang menyala', 'Menyalakan komputer dari keadaan mati total', 'Mematikan komputer', 'Menginstal sistem operasi'],
    ['BIOS adalah...', 'Program dasar di chip motherboard yang memeriksa hardware saat booting', 'Aplikasi pengolah kata', 'Web browser', 'Jenis game'],
    ['File adalah...', 'Kumpulan data yang disimpan dengan nama tertentu', 'Tempat untuk mengelompokkan folder fisik', 'Kabel data', 'Komponen hardware'],
    ['Folder berfungsi untuk...', 'Mengelompokkan dan merapikan file', 'Menjalankan program', 'Menghapus virus', 'Mempercepat prosesor'],
    ['File dengan ekstensi .docx adalah file...', 'Dokumen Microsoft Word', 'Gambar', 'Musik', 'Video'],
    ['File dengan ekstensi .jpg atau .png adalah file...', 'Gambar', 'Dokumen', 'Musik', 'Program'],
    ['File dengan ekstensi .mp3 adalah file...', 'Audio/musik', 'Video', 'Dokumen', 'Gambar'],
    ['File dengan ekstensi .mp4 adalah file...', 'Video', 'Audio saja', 'Teks', 'Gambar diam'],
    ['Fungsi shortcut Ctrl + C adalah...', 'Menyalin (copy)', 'Menempel (paste)', 'Memotong (cut)', 'Membatalkan (undo)'],
    ['Fungsi shortcut Ctrl + V adalah...', 'Menempel (paste)', 'Menyalin (copy)', 'Menyimpan (save)', 'Mencetak (print)'],
    ['Fungsi shortcut Ctrl + Z adalah...', 'Membatalkan perintah terakhir (undo)', 'Memperbesar tampilan', 'Menyimpan file', 'Menutup program'],
    ['Fungsi shortcut Ctrl + S adalah...', 'Menyimpan file', 'Memilih semua', 'Mencari kata', 'Mencetak'],
    ['Fungsi shortcut Ctrl + X adalah...', 'Memotong (cut)', 'Menyalin (copy)', 'Menempel (paste)', 'Keluar dari program'],
    ['Fungsi shortcut Ctrl + P adalah...', 'Mencetak (print)', 'Menempel (paste)', 'Menyimpan', 'Membuka file'],
    ['Fungsi shortcut Ctrl + A adalah...', 'Memilih semua (select all)', 'Menyalin', 'Menyimpan', 'Menebalkan huruf'],
    ['Tombol Caps Lock pada keyboard berfungsi untuk...', 'Mengaktifkan huruf kapital secara terus-menerus', 'Menghapus huruf', 'Membuat spasi', 'Membuat baris baru'],
    ['Tombol Backspace berfungsi untuk...', 'Menghapus karakter di sebelah kiri kursor', 'Menghapus karakter di sebelah kanan kursor', 'Membuat baris baru', 'Membuat huruf besar'],
    ['Klik kanan pada mouse biasanya digunakan untuk...', 'Menampilkan menu pilihan (menu konteks)', 'Mematikan komputer', 'Menutup semua program', 'Menyalakan monitor'],
    ['Klik dua kali (double-click) pada ikon biasanya digunakan untuk...', 'Membuka file atau menjalankan program', 'Menghapus file', 'Mengganti nama file', 'Mematikan komputer'],
    ['Drag and drop adalah...', 'Menekan dan menahan objek, menggesernya, lalu melepaskannya', 'Klik dua kali dengan cepat', 'Klik kanan pada objek', 'Memutar roda mouse'],
    ['Pada Windows, desktop adalah...', 'Tampilan layar utama tempat ikon, taskbar, dan wallpaper', 'Casing komputer', 'Nama aplikasi pengolah kata', 'Folder tersembunyi'],
    ['Taskbar pada Windows adalah...', 'Batang di bawah layar berisi tombol Start dan program yang sedang terbuka', 'Tempat file yang dihapus', 'Nama sebuah folder', 'Menu klik kanan'],
    ['Recycle Bin berfungsi sebagai...', 'Tempat sementara file yang dihapus dan masih bisa dikembalikan', 'Penyimpanan cloud', 'Antivirus', 'Memori RAM'],
    ['Laptop adalah jenis komputer yang...', 'Portabel dan dapat digunakan dengan baterai', 'Sangat besar dan memenuhi satu ruangan', 'Hanya untuk server', 'Tidak memiliki layar'],
    ['HP (smartphone) termasuk komputer karena...', 'Dapat menerima input, mengolah, menyimpan, dan menampilkan output', 'Hanya bisa digunakan untuk menelepon', 'Memiliki kamera', 'Tidak termasuk komputer'],
    ['Urutan siklus pengolahan data yang benar adalah...', 'Input, proses, output', 'Output, input, proses', 'Proses, output, input', 'Output, proses, input'],
    ['Posisi tubuh yang baik saat menggunakan komputer adalah...', 'Duduk tegak dengan jarak mata ke monitor sekitar 50-70 cm', 'Membungkuk sangat dekat ke layar', 'Berbaring di kasur', 'Di ruangan gelap tanpa lampu'],
    ['Virus komputer adalah...', 'Program jahat yang dapat merusak atau mengganggu kerja komputer', 'Kerusakan pada kabel', 'Debu di dalam casing', 'Pengguna komputer yang malas'],
    ['Cara mencegah virus komputer adalah...', 'Memasang antivirus dan tidak membuka file atau tautan mencurigakan', 'Sering mematikan komputer', 'Memakai software bajakan', 'Mencolokkan flashdisk sembarangan'],
    ['Contoh media penyimpanan cloud (awan) adalah...', 'Google Drive', 'Harddisk', 'Flashdisk', 'DVD'],
    ['DVD termasuk media penyimpanan optik karena data dibaca menggunakan...', 'Sinar laser', 'Magnet', 'Chip flash', 'Kabel USB'],
    ['Tokoh yang dijuluki "Bapak Komputer" adalah...', 'Charles Babbage', 'Bill Gates', 'Steve Jobs', 'Thomas Edison'],
    ['Susunan huruf yang paling umum pada keyboard komputer disebut...', 'QWERTY', 'ABCDEF', 'AZERTY', 'DVORAK'],
  ],

  kelas8: [
    ['HTML merupakan singkatan dari...', 'HyperText Markup Language', 'High Tech Modern Language', 'HyperText Making Link', 'Home Tool Markup Language'],
    ['HTML digunakan untuk...', 'Menyusun struktur dan isi halaman web', 'Mengedit foto', 'Membuat sistem operasi', 'Menghitung data di tabel Excel'],
    ['File HTML harus disimpan dengan ekstensi...', '.html', '.docx', '.exe', '.mp3'],
    ['Untuk melihat hasil kode HTML, file dibuka menggunakan...', 'Web browser seperti Chrome', 'Microsoft Excel', 'Kalkulator', 'Pemutar musik'],
    ['Tag penutup pada HTML ditandai dengan...', 'Garis miring, contoh </p>', 'Tanda seru, contoh <!p>', 'Titik, contoh <.p>', 'Tanda tanya, contoh <?p>'],
    ['Deklarasi yang ditulis di baris paling atas dokumen HTML5 adalah...', '<!DOCTYPE html>', '<html5>', '<start>', '<?html?>'],
    ['Tag yang membungkus seluruh isi dokumen HTML adalah...', '<html>', '<body>', '<head>', '<div>'],
    ['Bagian <head> pada HTML berisi...', 'Informasi halaman seperti judul tab dan meta, tidak tampil sebagai isi', 'Seluruh konten utama halaman', 'Bagian kaki (footer) halaman', 'Gambar-gambar halaman'],
    ['Bagian <body> pada HTML berisi...', 'Semua konten yang tampil di halaman web', 'Judul tab browser saja', 'Pengaturan meta saja', 'Kode rahasia'],
    ['Tag <title> berfungsi untuk...', 'Menampilkan judul pada tab browser', 'Membuat judul besar di dalam halaman', 'Membuat paragraf', 'Menyisipkan gambar'],
    ['Tag heading dengan ukuran paling besar adalah...', '<h1>', '<h6>', '<head>', '<p>'],
    ['Tag heading dengan ukuran paling kecil adalah...', '<h6>', '<h1>', '<h9>', '<h0>'],
    ['Tag untuk membuat paragraf adalah...', '<p>', '<para>', '<pg>', '<text>'],
    ['Tag untuk membuat baris baru (ganti baris) adalah...', '<br>', '<hr>', '<lb>', '<nl>'],
    ['Tag untuk membuat garis horizontal adalah...', '<hr>', '<br>', '<line>', '<hl>'],
    ['Tag untuk menebalkan teks adalah...', '<b> atau <strong>', '<i>', '<u>', '<s>'],
    ['Tag untuk memiringkan teks adalah...', '<i> atau <em>', '<b>', '<u>', '<br>'],
    ['Tag untuk memberi garis bawah pada teks adalah...', '<u>', '<ul>', '<i>', '<hr>'],
    ['Tag untuk menyisipkan gambar adalah...', '<img>', '<photo>', '<gbr>', '<src>'],
    ['Atribut pada tag <img> yang berisi alamat atau nama file gambar adalah...', 'src', 'href', 'alt', 'link'],
    ['Atribut alt pada tag <img> berfungsi untuk...', 'Menampilkan teks pengganti jika gambar gagal dimuat', 'Mengatur ukuran gambar', 'Menentukan alamat gambar', 'Memberi warna gambar'],
    ['Tag untuk membuat tautan (link) adalah...', '<a>', '<url>', '<go>', '<href>'],
    ['Atribut pada tag <a> yang berisi alamat tujuan link adalah...', 'href', 'src', 'alt', 'title'],
    ['Atribut target="_blank" pada link berfungsi untuk...', 'Membuka link di tab baru', 'Menutup halaman', 'Menyembunyikan link', 'Mencetak halaman'],
    ['Tag untuk membuat daftar berpoin (tidak berurutan) adalah...', '<ul>', '<ol>', '<li>', '<list>'],
    ['Tag untuk membuat daftar bernomor (berurutan) adalah...', '<ol>', '<ul>', '<li>', '<nl>'],
    ['Tag untuk menuliskan setiap item di dalam daftar adalah...', '<li>', '<item>', '<ul>', '<it>'],
    ['Tag untuk membuat tabel adalah...', '<table>', '<tab>', '<tr>', '<grid>'],
    ['Tag untuk membuat baris pada tabel adalah...', '<tr>', '<td>', '<th>', '<tb>'],
    ['Tag untuk membuat sel data pada tabel adalah...', '<td>', '<tr>', '<th>', '<cell>'],
    ['Tag untuk membuat sel judul (header) pada tabel adalah...', '<th>', '<td>', '<tr>', '<head>'],
    ['Atribut border="1" pada tabel berfungsi untuk...', 'Memberi garis tepi pada tabel', 'Memberi warna latar', 'Membuat judul tabel', 'Membuat link'],
    ['Penulisan komentar yang benar di HTML adalah...', '<!-- komentar -->', '// komentar', '# komentar', '** komentar **'],
    ['Komentar di dalam kode HTML berfungsi sebagai...', 'Catatan dalam kode yang tidak ditampilkan browser', 'Teks yang ditampilkan tebal', 'Penyebab error', 'Judul halaman'],
    ['Atribut pada HTML dituliskan di dalam...', 'Tag pembuka, contoh <img src="foto.jpg">', 'Tag penutup', 'Di luar tag', 'File terpisah'],
    ['Manakah pasangan tag yang tidak memerlukan tag penutup?', '<br> dan <img>', '<p> dan <h1>', '<ul> dan <li>', '<table> dan <tr>'],
    ['Penulisan tag bersarang (nested) yang benar adalah...', '<p><b>Halo</b></p>', '<p><b>Halo</p></b>', '<b><p>Halo</b></p>', '<p>Halo<b></p>'],
    ['CSS digunakan untuk...', 'Mengatur tampilan web seperti warna, huruf, dan tata letak', 'Menyusun struktur halaman', 'Menyimpan database', 'Membuat sistem operasi'],
    ['Penulisan atribut style yang benar adalah...', '<p style="color:red;">', '<p color=red>', '<p css="red">', '<p font="red">'],
    ['Properti CSS untuk mengubah warna teks adalah...', 'color', 'background-color', 'font-size', 'text-align'],
    ['Properti CSS untuk mengubah warna latar belakang adalah...', 'background-color', 'color', 'text-color', 'border'],
    ['Properti CSS untuk mengatur ukuran huruf adalah...', 'font-size', 'text-size', 'font-weight', 'size'],
    ['Kode CSS untuk membuat teks rata tengah adalah...', 'text-align: center;', 'align: middle;', 'center: true;', 'text-center: yes;'],
    ['Properti CSS untuk mengatur jenis huruf adalah...', 'font-family', 'font-type', 'text-font', 'typeface'],
    ['Kode warna #FF0000 menghasilkan warna...', 'Merah', 'Hijau', 'Biru', 'Hitam'],
    ['Kode warna #FFFFFF menghasilkan warna...', 'Putih', 'Hitam', 'Merah', 'Kuning'],
    ['Tag <div> berfungsi sebagai...', 'Wadah atau kotak untuk mengelompokkan elemen', 'Penyisip gambar', 'Pembuat link', 'Penebal teks'],
    ['Tag <span> berfungsi sebagai...', 'Wadah sebaris untuk menandai sebagian teks', 'Pembuat baris baru', 'Pembuat tabel', 'Pembuat judul besar'],
    ['Tag <form> digunakan untuk membuat...', 'Formulir isian bagi pengguna', 'Tabel', 'Gambar', 'Daftar bernomor'],
    ['Kode <input type="text"> menghasilkan...', 'Kotak isian teks', 'Tombol', 'Gambar', 'Link'],
    ['Tag <button> digunakan untuk membuat...', 'Tombol yang dapat diklik', 'Kotak teks panjang', 'Gambar', 'Paragraf'],
    ['Kode <input type="password"> menghasilkan kotak isian yang...', 'Isinya disamarkan menjadi titik atau bintang', 'Hanya menerima angka', 'Berwarna merah', 'Tidak bisa diisi'],
    ['Tag untuk menyisipkan video adalah...', '<video>', '<movie>', '<mp4>', '<play>'],
    ['Tag untuk menyisipkan suara/musik adalah...', '<audio>', '<sound>', '<music>', '<mp3>'],
    ['Atribut controls pada tag <video> berfungsi untuk...', 'Menampilkan tombol play, pause, dan volume', 'Memutar video otomatis', 'Menyembunyikan video', 'Mengulang video terus'],
    ['Kode <meta charset="UTF-8"> berfungsi untuk...', 'Mengatur pengkodean karakter agar huruf dan simbol tampil benar', 'Membuat judul halaman', 'Mengatur warna latar', 'Membuat link'],
    ['Meta viewport ditambahkan agar halaman web...', 'Menyesuaikan tampilan dengan ukuran layar HP', 'Lebih cepat diketik', 'Berwarna lebih cerah', 'Tidak bisa dibuka'],
    ['Kumpulan halaman web yang saling terhubung dalam satu domain disebut...', 'Website (situs web)', 'Web browser', 'Search engine', 'Hyperlink'],
    ['URL adalah...', 'Alamat sebuah halaman atau sumber di internet', 'Bahasa pemrograman', 'Aplikasi pengedit foto', 'Kabel jaringan'],
    ['Domain yang khusus digunakan untuk sekolah di Indonesia adalah...', '.sch.id', '.ac.id', '.go.id', '.or.id'],
    ['Web hosting adalah...', 'Layanan penyimpanan file website agar bisa diakses secara online', 'Aplikasi pembuat kode', 'Web browser', 'Antivirus'],
    ['Contoh layanan gratis untuk mengonlinekan website HTML sederhana adalah...', 'GitHub Pages', 'Microsoft Word', 'WhatsApp', 'Spotify'],
    ['Aplikasi di HP yang dapat digunakan untuk menulis kode HTML adalah...', 'Acode (code editor)', 'Kalkulator', 'Kamera', 'Galeri'],
    ['Saat menyimpan kode HTML di HP, penamaan file yang benar adalah...', 'index.html', 'index.html.txt', 'index', 'index.docx'],
    ['Jika file HTML tidak sengaja tersimpan sebagai .txt, maka saat dibuka...', 'Yang tampil hanya teks kode mentah, bukan halaman web', 'Halaman web tampil normal', 'HP langsung rusak', 'File otomatis terhapus'],
    ['Cara membuka file HTML yang sudah disimpan di HP adalah...', 'Buka lewat File Manager lalu pilih buka dengan browser', 'Buka lewat aplikasi Kamera', 'Buka lewat Kalkulator', 'Kirim ke nomor sendiri lewat SMS'],
    ['Nama file yang biasa digunakan untuk halaman utama website adalah...', 'index.html', 'home.docx', 'utama.txt', 'start.exe'],
    ['AI merupakan singkatan dari...', 'Artificial Intelligence', 'Automatic Internet', 'Advanced Information', 'Artificial Internet'],
    ['AI generatif adalah AI yang...', 'Dapat membuat konten baru seperti teks, gambar, dan kode dari perintah', 'Hanya dapat menghitung angka', 'Berupa robot fisik', 'Berfungsi sebagai antivirus'],
    ['Contoh chatbot AI yang dapat membantu menulis kode HTML adalah...', 'ChatGPT, Gemini, atau Claude', 'Microsoft Excel', 'Paint', 'VLC Media Player'],
    ['Prompt adalah...', 'Perintah atau instruksi yang kita berikan kepada AI', 'Hasil jawaban dari AI', 'Kode error di browser', 'Nama file HTML'],
    ['Ciri prompt yang baik untuk meminta kode HTML adalah...', 'Jelas dan spesifik: menyebut tujuan, isi, dan gaya tampilan', 'Sangat singkat, cukup "buat web"', 'Ditulis dengan kata acak', 'Dikosongkan saja'],
    ['Manakah prompt yang paling baik?', 'Buatkan kode HTML halaman profil sekolah berisi judul, foto, paragraf sejarah, dan daftar ekstrakurikuler bernuansa biru', 'web', 'buat sesuatu dong', 'html'],
    ['Setelah AI memberikan kode HTML, langkah yang tepat adalah...', 'Salin, simpan sebagai .html, buka di browser, lalu periksa dan perbaiki', 'Langsung dikumpulkan tanpa dicoba', 'Dihapus saja', 'Dipercaya 100% tanpa dicek'],
    ['Jika kode dari AI tidak tampil sesuai harapan, sebaiknya kita...', 'Menjelaskan masalahnya secara spesifik dan meminta AI memperbaikinya', 'Menyerah', 'Mengganti HP baru', 'Menghapus browser'],
    ['Istilah "halusinasi AI" berarti...', 'AI memberikan jawaban keliru yang terlihat meyakinkan', 'AI sedang tidur', 'AI terkena virus', 'AI kehabisan baterai'],
    ['Sikap yang benar saat memakai AI untuk tugas membuat website adalah...', 'Memahami kodenya dan jujur menyebutkan bahwa dibantu AI', 'Menyalin tanpa paham lalu mengaku buatan sendiri', 'Menjual kodenya ke teman', 'Tidak pernah memeriksa hasilnya'],
    ['Data yang tidak boleh dimasukkan ke dalam chatbot AI adalah...', 'Kata sandi dan data pribadi yang sensitif', 'Nama tag HTML', 'Warna favorit untuk website', 'Ide judul halaman'],
    ['Memperbaiki prompt secara bertahap sampai hasil AI sesuai keinginan disebut...', 'Iterasi prompt', 'Booting', 'Hosting', 'Debugging hardware'],
    ['Fitur "view source" atau "lihat sumber" pada browser digunakan untuk...', 'Melihat kode HTML dari sebuah halaman web', 'Menghapus halaman web', 'Mempercepat internet', 'Mencetak halaman'],
    ['Pada kode <a href="https://kemdikbud.go.id">Kemdikbud</a>, teks yang tampil dan dapat diklik adalah...', 'Kemdikbud', 'https://kemdikbud.go.id', 'a', 'href'],
    ['Hasil tampilan kode <h1>Halo</h1> di browser adalah...', 'Teks "Halo" berukuran besar dan tebal sebagai judul', 'Tulisan <h1>Halo</h1> apa adanya', 'Teks kecil dan miring', 'Tidak tampil apa-apa'],
    ['Pada kode <img src="kucing.jpg" alt="Kucing">, bagian kucing.jpg adalah...', 'Nama/alamat file gambar', 'Teks alternatif', 'Ukuran gambar', 'Judul halaman'],
    ['Atribut width pada tag <img> berfungsi untuk mengatur...', 'Lebar gambar', 'Alamat gambar', 'Teks pengganti', 'Garis tepi'],
    ['Gambar tidak muncul di halaman web. Penyebab paling mungkin adalah...', 'Nama atau lokasi file pada atribut src salah', 'Tag <body> terlalu panjang', 'Browser terlalu baru', 'Warna latar terlalu terang'],
    ['Urutan struktur dasar HTML yang benar adalah...', '<!DOCTYPE html>, <html>, <head>, <body>', '<body>, <head>, <html>, <!DOCTYPE html>', '<head>, <!DOCTYPE html>, <body>, <html>', '<html>, <body>, <!DOCTYPE html>, <head>'],
    ['Akibat yang umum terjadi jika kita lupa menutup tag, misalnya tag <b>, adalah...', 'Format tebal terbawa ke teks lain sehingga tampilan berantakan', 'HP menjadi rusak', 'File langsung terhapus', 'Tidak ada pengaruh sama sekali'],
    ['Jika kita mengetik lima spasi berturut-turut di dalam paragraf HTML, browser akan menampilkannya sebagai...', 'Satu spasi saja', 'Lima spasi', 'Baris baru', 'Error'],
    ['Untuk menampilkan tanda < sebagai teks di halaman web, digunakan kode entitas...', '&lt;', '&gt;', '&amp;', '&nbsp;'],
    ['Kode entitas &nbsp; menghasilkan...', 'Spasi yang tidak terputus', 'Baris baru', 'Tanda <', 'Simbol hak cipta'],
    ['Kode entitas &copy; menghasilkan simbol...', '©', '&', '<', '®'],
    ['Penulisan link untuk mengirim email yang benar adalah...', '<a href="mailto:guru@sekolah.sch.id">', '<a href="tel:guru@sekolah.sch.id">', '<a src="guru@sekolah.sch.id">', '<a email="guru@sekolah.sch.id">'],
    ['Hyperlink adalah...', 'Teks atau gambar yang bila diklik membuka halaman atau lokasi lain', 'Gambar biasa tanpa fungsi', 'Jenis huruf', 'Ukuran halaman'],
    ['Website yang responsif artinya...', 'Tampilannya menyesuaikan ukuran layar HP, tablet, maupun laptop', 'Hanya bisa dibuka di laptop', 'Hanya berwarna hitam putih', 'Tidak memiliki gambar'],
    ['Front-end developer adalah orang yang bertugas...', 'Membuat bagian tampilan website yang dilihat pengguna', 'Merakit hardware komputer', 'Memasang kabel listrik', 'Memperbaiki printer'],
    ['Bahasa yang biasa digunakan untuk membuat halaman web menjadi interaktif adalah...', 'JavaScript', 'HTML saja', 'Microsoft Word', 'Bahasa Inggris'],
    ['Atribut id dan class pada tag HTML berfungsi untuk...', 'Memberi nama pada elemen agar bisa diatur oleh CSS atau JavaScript', 'Mengatur ukuran file', 'Membuat link', 'Menghapus elemen'],
    ['Website statis adalah website yang...', 'Isinya tetap sama dan dibuat dari HTML/CSS tanpa database', 'Isinya berubah sesuai pengguna yang login', 'Tidak bisa dibuka', 'Hanya bisa dibuka offline'],
    ['Penemu World Wide Web (WWW) dan HTML adalah...', 'Tim Berners-Lee', 'Bill Gates', 'Mark Zuckerberg', 'Steve Jobs'],
    ['Saat menambahkan gambar dari internet ke website, sebaiknya kita...', 'Memakai gambar bebas lisensi atau buatan sendiri dan mencantumkan sumber', 'Mengambil gambar apa saja tanpa izin', 'Menghapus nama pembuatnya', 'Memakai gambar milik orang lalu mengaku buatan sendiri'],
  ],

  kelas9: [
    ['Presentasi adalah kegiatan...', 'Menyampaikan informasi atau ide kepada audiens', 'Menulis buku harian', 'Mengunduh aplikasi', 'Merakit komputer'],
    ['Presentasi yang bertujuan meyakinkan atau mengajak audiens melakukan sesuatu disebut presentasi...', 'Persuasif', 'Informatif', 'Deskriptif', 'Naratif'],
    ['Presentasi informatif bertujuan untuk...', 'Memberikan informasi atau pengetahuan kepada audiens', 'Mengajak audiens membeli produk', 'Menghibur dengan lelucon saja', 'Menguji audiens'],
    ['Contoh aplikasi untuk membuat presentasi adalah...', 'Microsoft PowerPoint', 'Microsoft Excel', 'Notepad', 'WinRAR'],
    ['Aplikasi presentasi online gratis buatan Google adalah...', 'Google Slides', 'Google Sheets', 'Google Docs', 'Google Maps'],
    ['Ekstensi file presentasi Microsoft PowerPoint adalah...', '.pptx', '.docx', '.xlsx', '.html'],
    ['Satu halaman di dalam presentasi disebut...', 'Slide', 'Sheet', 'Cell', 'Paragraf'],
    ['Contoh aplikasi AI yang dapat membuat slide presentasi otomatis dari perintah teks adalah...', 'Gamma', 'Kalkulator', 'Paint', 'WinRAR'],
    ['Fitur AI di Canva yang membantu membuat desain presentasi otomatis disebut...', 'Magic Design', 'Recycle Bin', 'Format Painter', 'Print Preview'],
    ['Copilot di Microsoft PowerPoint adalah fitur AI yang dapat...', 'Membantu membuat dan merangkum isi slide', 'Menghapus virus', 'Mengisi tinta printer', 'Menambah RAM'],
    ['Langkah pertama sebelum membuat presentasi dengan bantuan AI adalah...', 'Menentukan topik, tujuan, dan audiens', 'Langsung memilih animasi', 'Memilih warna baju', 'Mematikan internet'],
    ['Prompt yang baik untuk membuat presentasi sebaiknya menyebutkan...', 'Topik, jumlah slide, sasaran audiens, dan gaya bahasa', 'Merk HP yang dipakai', 'Harga kuota internet', 'Nama hewan peliharaan'],
    ['Manakah prompt yang paling baik untuk AI?', 'Buatkan kerangka presentasi 8 slide tentang bahaya sampah plastik untuk siswa SMP, bahasa santai, tiap slide 3 poin', 'presentasi plastik', 'buat slide', 'tolong'],
    ['Kerangka (outline) presentasi adalah...', 'Susunan garis besar isi setiap slide', 'Efek animasi', 'Jenis huruf', 'Warna latar'],
    ['Struktur presentasi yang baik terdiri dari...', 'Pembukaan, isi, dan penutup', 'Isi saja', 'Penutup saja', 'Judul dan animasi saja'],
    ['Slide pembuka (judul) biasanya berisi...', 'Judul presentasi dan nama penyaji', 'Kesimpulan akhir', 'Daftar pustaka', 'Sesi tanya jawab'],
    ['Slide penutup biasanya berisi...', 'Kesimpulan, ucapan terima kasih, dan sesi tanya jawab', 'Judul presentasi saja', 'Daftar isi', 'Biodata lengkap keluarga'],
    ['Aturan 6x6 dalam membuat slide artinya...', 'Maksimal sekitar 6 baris dan 6 kata per baris', 'Wajib 6 slide', 'Memakai 6 warna', 'Presentasi 6 menit'],
    ['Teks di dalam slide sebaiknya ditulis dalam bentuk...', 'Poin-poin singkat', 'Paragraf yang sangat panjang', 'Huruf kapital semua', 'Huruf yang sangat kecil'],
    ['Ukuran huruf isi slide yang disarankan agar terbaca dari belakang kelas adalah sekitar...', '24 pt atau lebih', '8 pt', '10 pt', '12 pt'],
    ['Jenis huruf yang mudah dibaca untuk slide adalah...', 'Huruf sans-serif seperti Arial atau Calibri', 'Huruf sambung yang sangat dekoratif', 'Huruf yang sangat tipis', 'Huruf bergaris-garis'],
    ['Kombinasi warna teks dan latar yang paling mudah dibaca adalah...', 'Teks gelap di atas latar terang', 'Teks kuning di atas latar putih', 'Teks merah di atas latar oranye', 'Teks abu-abu muda di atas latar putih'],
    ['Jumlah warna utama yang disarankan dalam satu desain presentasi adalah...', '2 sampai 3 warna yang serasi', '10 warna berbeda', 'Setiap slide warna acak', 'Tidak ada warna sama sekali'],
    ['Gambar yang dipakai dalam slide sebaiknya...', 'Relevan dengan materi dan tidak buram', 'Lucu walaupun tidak berhubungan', 'Buram dan kecil', 'Sebanyak mungkin dalam satu slide'],
    ['Transisi dalam presentasi adalah...', 'Efek perpindahan dari satu slide ke slide berikutnya', 'Efek gerak objek di dalam slide', 'Jenis huruf', 'Catatan pembicara'],
    ['Animasi dalam presentasi adalah...', 'Efek gerak pada objek di dalam slide', 'Efek perpindahan antarslide', 'Ukuran slide', 'Nama file'],
    ['Penggunaan animasi yang baik dalam presentasi adalah...', 'Secukupnya agar tidak mengganggu fokus audiens', 'Sebanyak mungkin di setiap objek', 'Yang paling lama durasinya', 'Yang bersuara paling keras'],
    ['Slide Master berfungsi untuk...', 'Mengatur tampilan dasar yang seragam untuk semua slide', 'Menghapus semua slide', 'Mencetak presentasi', 'Mengirim email'],
    ['Template atau tema presentasi adalah...', 'Desain siap pakai berisi paduan warna, huruf, dan tata letak', 'Isi materi presentasi', 'Nama penyaji', 'Daftar pustaka'],
    ['Presenter View berfungsi untuk...', 'Menampilkan catatan pembicara di layar penyaji, sementara audiens hanya melihat slide', 'Menghapus catatan', 'Mencetak slide', 'Mengubah warna tema'],
    ['Speaker notes (catatan pembicara) adalah...', 'Catatan untuk penyaji yang tidak tampil di layar audiens', 'Judul setiap slide', 'Teks yang tampil besar di slide', 'Daftar nama audiens'],
    ['Pada PowerPoint, tombol F5 berfungsi untuk...', 'Memulai slideshow dari slide pertama', 'Menyimpan file', 'Menutup aplikasi', 'Menambah slide'],
    ['Pada PowerPoint, Shift + F5 berfungsi untuk...', 'Memulai slideshow dari slide yang sedang dipilih', 'Menghapus slide', 'Mencetak slide', 'Menyimpan sebagai PDF'],
    ['Tombol Esc saat slideshow berlangsung berfungsi untuk...', 'Keluar dari mode slideshow', 'Menambah slide', 'Memperbesar huruf', 'Menyimpan file'],
    ['Pada PowerPoint, shortcut untuk menambah slide baru adalah...', 'Ctrl + M', 'Ctrl + S', 'Ctrl + P', 'Ctrl + Z'],
    ['Menyimpan presentasi dalam format PDF bermanfaat agar...', 'Tampilannya tetap sama saat dibuka di perangkat lain', 'Animasinya bertambah', 'Ukuran slide berubah', 'Isinya bisa diedit siapa saja'],
    ['Halusinasi AI dalam pembuatan materi presentasi berarti...', 'AI membuat informasi yang salah tetapi terdengar meyakinkan', 'AI menampilkan gambar bergerak', 'AI bekerja sangat cepat', 'AI menolak semua perintah'],
    ['Karena AI bisa berhalusinasi, siswa sebaiknya...', 'Mengecek kembali fakta ke sumber terpercaya', 'Langsung percaya semua jawaban AI', 'Tidak membaca hasil AI', 'Menambah animasi'],
    ['Manakah yang termasuk sumber informasi terpercaya?', 'Situs resmi pemerintah, buku, dan jurnal ilmiah', 'Komentar anonim di media sosial', 'Pesan berantai di grup chat', 'Judul video yang heboh'],
    ['Sikap etis saat membuat presentasi dengan bantuan AI adalah...', 'Menyebutkan bahwa presentasi dibantu AI dan mencantumkan sumber', 'Mengaku semuanya hasil kerja sendiri', 'Menyalin presentasi teman', 'Menghapus nama sumber'],
    ['Plagiarisme adalah...', 'Mengambil karya orang lain tanpa menyebut sumber dan mengakuinya sebagai milik sendiri', 'Membuat karya sendiri', 'Mengutip dengan mencantumkan sumber', 'Bertanya kepada guru'],
    ['Data yang tidak boleh diunggah ke aplikasi AI adalah...', 'Data pribadi seperti NIK, alamat rumah, dan kata sandi', 'Topik presentasi', 'Judul slide', 'Jumlah slide yang diinginkan'],
    ['Peran siswa saat membuat presentasi dengan AI adalah...', 'Sebagai pengarah dan pemeriksa akhir, AI hanya alat bantu', 'Menyerahkan semuanya kepada AI tanpa dicek', 'Hanya menekan tombol tanpa membaca', 'Tidak perlu memahami isi'],
    ['Jenis AI yang mengubah perintah teks menjadi gambar disebut...', 'Text-to-image', 'Text-to-speech', 'Speech-to-text', 'Image-to-text'],
    ['Teknologi text-to-speech berfungsi untuk...', 'Mengubah teks menjadi suara', 'Mengubah suara menjadi teks', 'Mengubah gambar menjadi video', 'Mengubah video menjadi gambar'],
    ['Teknologi speech-to-text berfungsi untuk...', 'Mengubah ucapan menjadi teks tulisan', 'Mengubah teks menjadi suara', 'Mengubah teks menjadi gambar', 'Mengubah slide menjadi PDF'],
    ['Cara terbaik merangkum materi panjang menjadi isi slide dengan AI adalah...', 'Meminta AI meringkas menjadi beberapa poin utama, lalu memeriksanya', 'Menyalin seluruh paragraf ke satu slide', 'Menghapus semua materi', 'Membuat slide kosong'],
    ['Jika hasil AI terlalu umum dan tidak sesuai harapan, sebaiknya kita...', 'Memberi prompt yang lebih spesifik dan lengkap konteksnya', 'Langsung memakainya', 'Berhenti mengerjakan tugas', 'Memakai prompt yang lebih pendek'],
    ['Menulis "Bertindaklah sebagai guru biologi" di awal prompt bertujuan untuk...', 'Mengarahkan gaya dan sudut pandang jawaban AI', 'Membuat AI menjadi manusia', 'Mempercepat internet', 'Mengubah bahasa komputer'],
    ['Jika audiens presentasi adalah siswa SD, maka isi presentasi sebaiknya...', 'Memakai bahasa sederhana dan banyak gambar', 'Penuh istilah teknis', 'Berisi paragraf panjang', 'Tanpa gambar sama sekali'],
    ['Untuk presentasi berdurasi 10 menit, jumlah slide yang ideal adalah sekitar...', '8 sampai 12 slide', '50 slide', '1 slide', '100 slide'],
    ['Saat berpresentasi, penyaji sebaiknya...', 'Menjaga kontak mata dengan audiens dan tidak terus membaca slide', 'Membelakangi audiens', 'Membaca semua teks slide kata per kata', 'Berbicara sangat pelan'],
    ['Intonasi yang baik saat presentasi adalah...', 'Suara jelas dan bervariasi, tidak monoton', 'Berbisik', 'Berteriak terus-menerus', 'Datar tanpa perubahan'],
    ['Cara terbaik mengatasi rasa gugup sebelum presentasi adalah...', 'Mempersiapkan materi dan berlatih berulang kali', 'Tidak berlatih sama sekali', 'Datang terlambat', 'Menghafal tanpa memahami'],
    ['Jika ada pertanyaan audiens yang tidak bisa kita jawab, sikap terbaik adalah...', 'Jujur mengakui dan berjanji mencari tahu jawabannya', 'Mengarang jawaban', 'Mengabaikan penanya', 'Marah kepada penanya'],
    ['Alat presentasi yang digunakan untuk berpindah slide dari jarak jauh disebut...', 'Clicker atau remote presenter', 'Scanner', 'Webcam', 'Printer'],
    ['Sebelum tampil presentasi di kelas, hal yang perlu dicek adalah...', 'Proyektor, kabel HDMI, dan file cadangan', 'Warna sepatu', 'Saldo e-wallet', 'Jumlah followers'],
    ['Cara menyimpan cadangan file presentasi yang aman adalah...', 'Menyimpan di flashdisk dan di penyimpanan cloud seperti Google Drive', 'Hanya disimpan di satu tempat', 'Tidak perlu disimpan', 'Dikirim ke orang asing'],
    ['Kelebihan Google Slides untuk tugas kelompok adalah...', 'Beberapa orang dapat mengedit bersamaan melalui tautan berbagi', 'Hanya bisa dibuka satu orang', 'Tidak butuh perangkat apa pun', 'Tidak bisa disimpan'],
    ['Jika file Google Slides dibagikan dengan akses "Pelihat (Viewer)", penerima dapat...', 'Hanya melihat tanpa bisa mengedit', 'Mengedit semua isi', 'Menghapus file', 'Mengganti pemilik file'],
    ['Infografis adalah...', 'Penyajian informasi dalam bentuk visual yang ringkas dan menarik', 'Teks panjang tanpa gambar', 'Jenis huruf', 'Aplikasi antivirus'],
    ['Data berupa angka sebaiknya ditampilkan dalam slide menggunakan...', 'Grafik atau diagram', 'Paragraf panjang', 'Huruf sangat kecil', 'Animasi berlebihan'],
    ['Diagram batang paling cocok untuk...', 'Membandingkan jumlah antar kategori', 'Menunjukkan persentase dari keseluruhan', 'Menampilkan foto', 'Menulis kesimpulan'],
    ['Diagram lingkaran (pie chart) paling cocok untuk...', 'Menunjukkan bagian atau persentase dari keseluruhan', 'Menunjukkan tren dari waktu ke waktu', 'Menulis paragraf', 'Menampilkan video'],
    ['Diagram garis paling cocok untuk...', 'Menunjukkan perubahan atau tren dari waktu ke waktu', 'Menunjukkan persentase dari keseluruhan', 'Menampilkan peta', 'Menulis judul'],
    ['Storytelling dalam presentasi artinya...', 'Menyajikan materi seperti alur cerita agar lebih menarik', 'Membaca dongeng tanpa hubungan materi', 'Menghafal seluruh slide', 'Memutar musik keras'],
    ['Call to action pada presentasi persuasif adalah...', 'Ajakan kepada audiens untuk melakukan sesuatu di akhir presentasi', 'Judul slide pertama', 'Daftar pustaka', 'Efek transisi'],
    ['Pembukaan presentasi yang menarik perhatian (hook) contohnya adalah...', 'Pertanyaan atau fakta mengejutkan yang berhubungan dengan topik', 'Langsung membaca daftar pustaka', 'Diam selama satu menit', 'Meminta maaf berkali-kali'],
    ['Konsistensi desain presentasi artinya...', 'Jenis huruf, warna, dan tata letak seragam di semua slide', 'Setiap slide memakai tema berbeda', 'Setiap slide memakai huruf berbeda', 'Warna acak setiap slide'],
    ['Ruang kosong (white space) pada slide bermanfaat agar...', 'Slide terlihat rapi dan audiens fokus pada isi penting', 'Slide terlihat kosong tanpa makna', 'File menjadi rusak', 'Animasi lebih banyak'],
    ['Hierarki visual pada slide contohnya adalah...', 'Judul dibuat lebih besar dari teks isi', 'Semua teks berukuran sama', 'Teks isi lebih besar dari judul', 'Judul disembunyikan'],
    ['Gambar beresolusi rendah sebaiknya dihindari karena...', 'Akan pecah atau buram saat ditampilkan di proyektor', 'Ukurannya terlalu besar', 'Warnanya terlalu cerah', 'Tidak bisa disisipkan'],
    ['Sumber gambar yang diambil dari internet sebaiknya dicantumkan...', 'Di bawah gambar atau di slide daftar pustaka', 'Tidak perlu dicantumkan', 'Disembunyikan', 'Di nama file saja'],
    ['Lisensi Creative Commons artinya...', 'Izin memakai karya dengan syarat tertentu, misalnya menyebut nama pembuatnya', 'Karya yang dilarang dipakai sama sekali', 'Karya yang wajib dibeli mahal', 'Karya yang tidak memiliki pembuat'],
    ['Contoh situs penyedia foto gratis untuk presentasi adalah...', 'Unsplash atau Pixabay', 'Microsoft Excel', 'WhatsApp', 'Kalkulator'],
    ['Rasio ukuran slide layar lebar (widescreen) yang umum digunakan saat ini adalah...', '16:9', '4:3', '1:1', '21:1'],
    ['Hyperlink pada slide berfungsi untuk...', 'Menghubungkan ke slide lain atau ke sebuah website', 'Menghapus slide', 'Mengubah warna latar', 'Mematikan proyektor'],
    ['Menu yang digunakan untuk menyisipkan gambar atau video ke slide PowerPoint adalah...', 'Insert', 'Review', 'View', 'File'],
    ['Format PDF lebih cocok dipilih daripada PPTX ketika...', 'Presentasi hanya dibagikan untuk dibaca dan tidak memerlukan animasi', 'Presentasi masih perlu diedit bersama', 'Ingin menampilkan animasi', 'Ingin menambah transisi'],
    ['AI dapat membantu persiapan sesi tanya jawab dengan cara...', 'Membuat daftar kemungkinan pertanyaan audiens untuk latihan', 'Menjawab langsung di depan kelas menggantikan siswa', 'Mematikan mikrofon', 'Menghapus pertanyaan audiens'],
    ['Bias pada AI artinya...', 'AI dapat mencerminkan prasangka atau ketidakadilan dari data latihnya', 'AI selalu netral sempurna', 'AI tidak memiliki data', 'AI hanya bekerja malam hari'],
    ['AI seperti chatbot dapat menjawab pertanyaan karena...', 'Dilatih menggunakan data dalam jumlah sangat besar', 'Memiliki perasaan seperti manusia', 'Dikendalikan langsung oleh guru', 'Membaca pikiran pengguna'],
    ['Contoh chatbot AI yang dapat membantu menyusun isi presentasi adalah...', 'ChatGPT, Gemini, atau Copilot', 'Microsoft Paint', 'Windows Explorer', 'VLC Media Player'],
    ['Urutan alur kerja membuat presentasi dengan AI yang tepat adalah...', 'Tentukan topik, tulis prompt, buat draf, periksa dan sunting, latihan, presentasikan', 'Presentasikan, tulis prompt, tentukan topik, latihan', 'Latihan, presentasikan, tentukan topik, tulis prompt', 'Sunting, presentasikan, tulis prompt, tentukan topik'],
    ['Kegiatan menyunting hasil presentasi dari AI meliputi...', 'Mengecek fakta, menyesuaikan bahasa, dan menambah contoh nyata', 'Menambah animasi sebanyak-banyaknya', 'Menghapus nama penyaji', 'Membiarkan apa adanya'],
    ['Jika desain slide hasil AI terlihat berantakan, langkah yang tepat adalah...', 'Merapikan tata letak secara manual dan memakai tema yang konsisten', 'Membiarkannya saja', 'Menambah warna lebih banyak', 'Menghapus semua slide'],
    ['Alasan tidak menyalin seluruh jawaban AI langsung ke slide adalah...', 'Terlalu panjang untuk slide dan belum tentu benar', 'Jawaban AI selalu pendek', 'Slide tidak bisa menerima teks', 'AI melarangnya'],
    ['Bullet point dalam slide adalah...', 'Daftar poin singkat yang diawali tanda atau simbol', 'Paragraf panjang', 'Gambar latar', 'Efek suara'],
    ['Menambahkan teks alternatif (alt text) pada gambar di slide bermanfaat untuk...', 'Membantu pengguna tunanetra yang memakai pembaca layar', 'Memperbesar gambar', 'Menambah animasi', 'Mengganti warna'],
    ['Presentasi yang memperhatikan aksesibilitas artinya...', 'Dapat dipahami oleh semua orang, termasuk yang berkebutuhan khusus', 'Hanya bisa dibuka oleh guru', 'Hanya untuk orang dewasa', 'Memiliki banyak animasi'],
    ['Fitur subtitle atau teks langsung (live caption) saat presentasi bermanfaat untuk...', 'Membantu audiens tunarungu dan memperjelas ucapan penyaji', 'Mengganti suara penyaji', 'Mematikan slide', 'Menyimpan file'],
    ['Fitur AI di PowerPoint yang memberi masukan tentang kecepatan bicara dan kata pengisi saat latihan adalah...', 'Speaker Coach', 'Slide Sorter', 'Format Painter', 'Spelling Check'],
    ['Fitur Format Painter digunakan untuk...', 'Menyalin format dari satu objek ke objek lain', 'Menggambar bebas', 'Menghapus slide', 'Menyimpan sebagai PDF'],
    ['Tampilan Slide Sorter digunakan untuk...', 'Melihat semua slide dalam ukuran kecil dan mengatur urutannya', 'Menulis catatan pembicara', 'Menjalankan slideshow', 'Mencetak slide'],
    ['Kata pengisi seperti "eee" dan "anu" saat presentasi sebaiknya...', 'Dikurangi agar penyampaian lebih jelas', 'Diperbanyak', 'Diucapkan di setiap kalimat', 'Diganti dengan berteriak'],
    ['Umpan balik (feedback) setelah presentasi bermanfaat untuk...', 'Memperbaiki kualitas presentasi berikutnya', 'Menyalahkan audiens', 'Menghapus presentasi', 'Menghindari latihan'],
    ['Presentasi dinilai baik apabila...', 'Isinya akurat, desainnya jelas, dan penyampaiannya menarik', 'Jumlah animasinya paling banyak', 'Slidenya paling banyak', 'Hurufnya paling kecil'],
    ['Chatbot AI buatan Google adalah...', 'Gemini', 'Excel', 'Photoshop', 'Zoom'],
    ['Ketika AI menyebutkan sebuah data statistik untuk slide, sikap yang tepat adalah...', 'Mencari sumber asli data tersebut sebelum dipakai', 'Langsung memakainya tanpa sumber', 'Mengubah angkanya sesuka hati', 'Menghapus semua angka'],
    ['Teknik menjelaskan satu ide pokok per slide bertujuan agar...', 'Audiens lebih mudah memahami dan mengingat', 'Slide menjadi penuh tulisan', 'Presentasi lebih lama', 'Penyaji tidak perlu berbicara'],
  ],
};
